#!/bin/bash
# Generate Spanish audio files using macOS 'say' command (MVP quality).
# Run: bash scripts/generate-audio.sh
# Requires: macOS with Paulina voice installed
#   System Settings → Accessibility → Spoken Content → System Voice → Manage Voices → Spanish (Mexico) → Paulina
# Output: public/audio/sensei/, public/audio/vocab/, public/audio/instructions/

set -euo pipefail

VOICE="Paulina"
RATE=160
BASE="public/audio"

mkdir -p "$BASE/sensei" "$BASE/vocab" "$BASE/instructions" "$BASE/sfx"

convert_to_mp3() {
  local aiff="$1"
  local mp3="${aiff%.aiff}.mp3"
  if command -v ffmpeg &>/dev/null; then
    ffmpeg -y -i "$aiff" -codec:a libmp3lame -qscale:a 4 "$mp3" 2>/dev/null
    rm "$aiff"
  elif command -v afconvert &>/dev/null; then
    afconvert -d aac -f m4af "$aiff" "${aiff%.aiff}.m4a" 2>/dev/null
    rm "$aiff"
  else
    echo "  [warn] No ffmpeg or afconvert — keeping AIFF: $aiff"
  fi
}

gen() {
  local text="$1"
  local outpath="$2"
  local aiff="${outpath%.mp3}.aiff"
  echo "  Generating: $text → $outpath"
  say -v "$VOICE" -r "$RATE" "$text" -o "$aiff"
  convert_to_mp3 "$aiff"
}

echo "=== Generating Sensei Phrases ==="
gen "¡Hola, guerrero!" "$BASE/sensei/hola_guerrero.mp3"
gen "¡Bienvenido al Dojo!" "$BASE/sensei/bienvenido_dojo.mp3"
gen "¿Listo para entrenar?" "$BASE/sensei/listo.mp3"
gen "¡Vamos!" "$BASE/sensei/vamos.mp3"
gen "¡Muy bien!" "$BASE/sensei/muy_bien.mp3"
gen "¡Excelente!" "$BASE/sensei/excelente.mp3"
gen "¡Otra vez!" "$BASE/sensei/otra_vez.mp3"
gen "Entrena duro." "$BASE/sensei/entrena_duro.mp3"
gen "¡Entrenaste muy bien hoy!" "$BASE/sensei/entrenaste_bien.mp3"
gen "Tu disciplina es impresionante, guerrero." "$BASE/sensei/disciplina.mp3"
gen "¡Golpe perfecto!" "$BASE/sensei/golpe_perfecto.mp3"
gen "¡Fuerte!" "$BASE/sensei/fuerte.mp3"
gen "No te rindas." "$BASE/sensei/no_rindas.mp3"
gen "¡Tú puedes!" "$BASE/sensei/tu_puedes.mp3"
gen "¡Has ganado un nuevo cinturón!" "$BASE/sensei/nuevo_cinturon.mp3"
gen "¡Entrenamiento completo!" "$BASE/sensei/entrenamiento_completo.mp3"
gen "Descansa. Mañana entrenamos de nuevo." "$BASE/sensei/descansa.mp3"
gen "Muéstrame lo que sabes, guerrero." "$BASE/sensei/muestrame.mp3"

echo ""
echo "=== Generating Vocabulary Audio ==="

# Unit 1 - Greetings
gen "hola" "$BASE/vocab/hola.mp3"
gen "adiós" "$BASE/vocab/adios.mp3"
gen "me llamo" "$BASE/vocab/me-llamo.mp3"
gen "¿cómo te llamas?" "$BASE/vocab/como-te-llamas.mp3"
gen "buenos días" "$BASE/vocab/buenos-dias.mp3"
gen "buenas noches" "$BASE/vocab/buenas-noches.mp3"
gen "por favor" "$BASE/vocab/por-favor.mp3"
gen "gracias" "$BASE/vocab/gracias.mp3"
gen "buenas tardes" "$BASE/vocab/buenas-tardes.mp3"
gen "de nada" "$BASE/vocab/de-nada.mp3"
gen "mucho gusto" "$BASE/vocab/mucho-gusto.mp3"
gen "lo siento" "$BASE/vocab/lo-siento.mp3"
gen "con permiso" "$BASE/vocab/con-permiso.mp3"
gen "señor" "$BASE/vocab/senor.mp3"
gen "señora" "$BASE/vocab/senora.mp3"
gen "¿cómo estás?" "$BASE/vocab/como-estas.mp3"
gen "bien" "$BASE/vocab/bien.mp3"
gen "mal" "$BASE/vocab/mal.mp3"

# Unit 2 - Numbers
gen "cero" "$BASE/vocab/cero.mp3"
gen "uno" "$BASE/vocab/uno.mp3"
gen "dos" "$BASE/vocab/dos.mp3"
gen "tres" "$BASE/vocab/tres.mp3"
gen "cuatro" "$BASE/vocab/cuatro.mp3"
gen "cinco" "$BASE/vocab/cinco.mp3"
gen "seis" "$BASE/vocab/seis.mp3"
gen "siete" "$BASE/vocab/siete.mp3"
gen "ocho" "$BASE/vocab/ocho.mp3"
gen "nueve" "$BASE/vocab/nueve.mp3"
gen "diez" "$BASE/vocab/diez.mp3"
gen "once" "$BASE/vocab/once.mp3"
gen "doce" "$BASE/vocab/doce.mp3"
gen "trece" "$BASE/vocab/trece.mp3"
gen "catorce" "$BASE/vocab/catorce.mp3"
gen "quince" "$BASE/vocab/quince.mp3"
gen "dieciséis" "$BASE/vocab/dieciseis.mp3"
gen "diecisiete" "$BASE/vocab/diecisiete.mp3"
gen "dieciocho" "$BASE/vocab/dieciocho.mp3"
gen "diecinueve" "$BASE/vocab/diecinueve.mp3"
gen "veinte" "$BASE/vocab/veinte.mp3"
gen "treinta" "$BASE/vocab/treinta.mp3"
gen "cien" "$BASE/vocab/cien.mp3"
gen "¿cuántos años tienes?" "$BASE/vocab/cuantos-anos.mp3"

# Unit 3 - Colors
gen "rojo" "$BASE/vocab/rojo.mp3"
gen "azul" "$BASE/vocab/azul.mp3"
gen "verde" "$BASE/vocab/verde.mp3"
gen "amarillo" "$BASE/vocab/amarillo.mp3"
gen "blanco" "$BASE/vocab/blanco.mp3"
gen "negro" "$BASE/vocab/negro.mp3"
gen "grande" "$BASE/vocab/grande.mp3"
gen "pequeño" "$BASE/vocab/pequeno.mp3"
gen "bonito" "$BASE/vocab/bonito.mp3"
gen "morado" "$BASE/vocab/morado.mp3"
gen "rosado" "$BASE/vocab/rosado.mp3"
gen "gris" "$BASE/vocab/gris.mp3"
gen "anaranjado" "$BASE/vocab/anaranjado.mp3"
gen "lindo" "$BASE/vocab/lindo.mp3"
gen "simpático" "$BASE/vocab/simpatico.mp3"
gen "amable" "$BASE/vocab/amable.mp3"
gen "feo" "$BASE/vocab/feo.mp3"
gen "alto" "$BASE/vocab/alto.mp3"
gen "bajo" "$BASE/vocab/bajo.mp3"
gen "nuevo" "$BASE/vocab/nuevo.mp3"
gen "viejo" "$BASE/vocab/viejo.mp3"
gen "es" "$BASE/vocab/es.mp3"

# Unit 4 - Family
gen "mamá" "$BASE/vocab/mama.mp3"
gen "papá" "$BASE/vocab/papa.mp3"
gen "hermano" "$BASE/vocab/hermano.mp3"
gen "hermana" "$BASE/vocab/hermana.mp3"
gen "abuelo" "$BASE/vocab/abuelo.mp3"
gen "abuela" "$BASE/vocab/abuela.mp3"
gen "familia" "$BASE/vocab/familia.mp3"
gen "tío" "$BASE/vocab/tio.mp3"
gen "tía" "$BASE/vocab/tia.mp3"
gen "primo" "$BASE/vocab/primo.mp3"
gen "prima" "$BASE/vocab/prima.mp3"
gen "hijo" "$BASE/vocab/hijo.mp3"
gen "hija" "$BASE/vocab/hija.mp3"
gen "bebé" "$BASE/vocab/bebe.mp3"
gen "esposo" "$BASE/vocab/esposo.mp3"
gen "esposa" "$BASE/vocab/esposa.mp3"
gen "sobrino" "$BASE/vocab/sobrino.mp3"
gen "sobrina" "$BASE/vocab/sobrina.mp3"
gen "mi" "$BASE/vocab/mi.mp3"

# Unit 5 - Body
gen "cabeza" "$BASE/vocab/cabeza.mp3"
gen "mano" "$BASE/vocab/mano.mp3"
gen "pie" "$BASE/vocab/pie.mp3"
gen "ojo" "$BASE/vocab/ojo.mp3"
gen "boca" "$BASE/vocab/boca.mp3"
gen "me duele" "$BASE/vocab/me-duele.mp3"
gen "estoy bien" "$BASE/vocab/estoy-bien.mp3"
gen "brazo" "$BASE/vocab/brazo.mp3"
gen "pierna" "$BASE/vocab/pierna.mp3"
gen "dedo" "$BASE/vocab/dedo.mp3"
gen "nariz" "$BASE/vocab/nariz.mp3"
gen "oreja" "$BASE/vocab/oreja.mp3"
gen "estómago" "$BASE/vocab/estomago.mp3"
gen "espalda" "$BASE/vocab/espalda.mp3"
gen "rodilla" "$BASE/vocab/rodilla.mp3"
gen "cuello" "$BASE/vocab/cuello.mp3"

# Unit 6 - Animals
gen "perro" "$BASE/vocab/perro.mp3"
gen "gato" "$BASE/vocab/gato.mp3"
gen "pájaro" "$BASE/vocab/pajaro.mp3"
gen "pez" "$BASE/vocab/pez.mp3"
gen "caballo" "$BASE/vocab/caballo.mp3"
gen "vaca" "$BASE/vocab/vaca.mp3"
gen "cerdo" "$BASE/vocab/cerdo.mp3"
gen "conejo" "$BASE/vocab/conejo.mp3"
gen "ratón" "$BASE/vocab/raton.mp3"
gen "tortuga" "$BASE/vocab/tortuga.mp3"
gen "mariposa" "$BASE/vocab/mariposa.mp3"
gen "mono" "$BASE/vocab/mono.mp3"
gen "oso" "$BASE/vocab/oso.mp3"

# Unit 7 - Food
gen "manzana" "$BASE/vocab/manzana.mp3"
gen "agua" "$BASE/vocab/agua.mp3"
gen "leche" "$BASE/vocab/leche.mp3"
gen "pan" "$BASE/vocab/pan.mp3"
gen "pollo" "$BASE/vocab/pollo.mp3"
gen "me gusta" "$BASE/vocab/me-gusta.mp3"
gen "no me gusta" "$BASE/vocab/no-me-gusta.mp3"
gen "arroz" "$BASE/vocab/arroz.mp3"
gen "frijoles" "$BASE/vocab/frijoles.mp3"
gen "huevo" "$BASE/vocab/huevo.mp3"
gen "queso" "$BASE/vocab/queso.mp3"
gen "fruta" "$BASE/vocab/fruta.mp3"
gen "jugo" "$BASE/vocab/jugo.mp3"
gen "café" "$BASE/vocab/cafe.mp3"
gen "carne" "$BASE/vocab/carne.mp3"
gen "ensalada" "$BASE/vocab/ensalada.mp3"
gen "sopa" "$BASE/vocab/sopa.mp3"

# Unit 8 - School
gen "libro" "$BASE/vocab/libro.mp3"
gen "lápiz" "$BASE/vocab/lapiz.mp3"
gen "escuela" "$BASE/vocab/escuela.mp3"
gen "maestro" "$BASE/vocab/maestro.mp3"
gen "maestra" "$BASE/vocab/maestra.mp3"
gen "clase" "$BASE/vocab/clase.mp3"
gen "puerta" "$BASE/vocab/puerta.mp3"
gen "ventana" "$BASE/vocab/ventana.mp3"
gen "mesa" "$BASE/vocab/mesa.mp3"
gen "silla" "$BASE/vocab/silla.mp3"
gen "pizarra" "$BASE/vocab/pizarra.mp3"
gen "mochila" "$BASE/vocab/mochila.mp3"
gen "cuaderno" "$BASE/vocab/cuaderno.mp3"
gen "tarea" "$BASE/vocab/tarea.mp3"
gen "examen" "$BASE/vocab/examen.mp3"
gen "recreo" "$BASE/vocab/recreo.mp3"
gen "¿puedo ir al baño?" "$BASE/vocab/puedo-ir.mp3"

echo ""
echo "=== Generating Instruction Phrases ==="
gen "Toca la imagen correcta" "$BASE/instructions/tap_image.mp3"
gen "Escucha y elige" "$BASE/instructions/listen_choose.mp3"
gen "Di esta palabra" "$BASE/instructions/say_word.mp3"
gen "Completa la oración" "$BASE/instructions/complete_sentence.mp3"
gen "Traduce la frase" "$BASE/instructions/translate.mp3"
gen "Conecta las parejas" "$BASE/instructions/match_pairs.mp3"
gen "Ordena las palabras" "$BASE/instructions/order_words.mp3"

echo ""
echo "=== Done! ==="
echo "Generated audio files in $BASE/"
echo "If you have ffmpeg installed, files are in MP3 format."
echo "Otherwise, they remain as AIFF (still playable in browsers)."
